feedback_form/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path('ajax/validate-feedback-form/', feedback_form_view, name='ajax_feedback_form_validation'),
    path('ajax/confirm-email/', confirm_email_view_initial, name='ajax_email_confirmation'),
    path('ajax/reconfirm-email/', confirm_email_view_secondary, name='ajax_email_reconfirmation'),
    path('ajax/validate-confirmation-code/', validate_code_view, name='ajax_code_validation'),
    path('form_success/', form_success_view, name='form_success')
]

feedback_form/forms.py
import logging

from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone

from .models import FeedbackFormSession
from .utils import hash_value

logger = logging.getLogger('feedback_form_app_logger')  # getting the logger to log stuff


class FeedbackForm(forms.Form):
    """
    A feedback form that allows a user to send an email message to a staff member.
    User must enter the email and confirm it (this logic is implemented in the views
    and on the frontend). The form works with the FeedbackFormSession model that saves
    the state of the user's session with the form. FeedbackForm performs a validation
    based on the model object retrieved from the db using the 'session_identifier'
    argument provided within the initializer method.
    """
    email = forms.EmailField()
    code = forms.DecimalField()
    message = forms.CharField()

    def __init__(self, *args, **kwargs):
        # fetching the 'session_identifier' argument and preventing it from
        # going further into the super class. 'session_identifier' is an identifier
        # used to retrieve the model instance needed to perform a validation with the db
        session_identifier = kwargs.pop('session_identifier', None)

        super().__init__(*args, **kwargs)

        if session_identifier is None:
            # the form was initialized without providing the 'session_identifier' argument
            # which probably means that it was initialized the wrong way or somehow accidentally
            logger.error('The FeedbackForm object was initialized without providing the "session_identifier" argument!')
            
            self.no_identifier = True
            self.critical_error = True

        else:
            session_identifier = hash_value(session_identifier)
            session_record = FeedbackFormSession.objects.filter(session_identifier=session_identifier).first()
            self.session_record = session_record

    def clean(self):
        if hasattr(self, 'no_identifier'):
            # the form object has no session identifier
            self.add_error(None, ValidationError(
                message='Critical error occurred while trying to process the form.',
                code='no_identifier'
            ))
            return None

        cleaned_data = super().clean()

        if self.session_record is None:
            # session record object does not exist
            # this shouldn't be reachable to the user, so most likely some error or abuse
            self.add_error(None, ValidationError(
                message='Critical error occurred while trying to process the form.',
                code='no_record'
            ))
            logger.warning('Session record with the session_identifier provided to the form object does not exist! '
                           'Seems like an abuse or an error.')
            self.critical_error = True

        if self.errors:
            if self.errors.get('email', False):
                # it is what it is...
                self.critical_error = True
            return cleaned_data

        if not self.session_record.submission_attempts_left:
            # user has no submission attempts left
            # this is used to prevent a spam with submissions
            self.add_error(None, ValidationError(
                message='The number of available attempts to send a message has been exhausted. '
                        'Please try requesting the code again.', code='no_attempts_left'
            ))
            self.session_record.delete()
            self.critical_error = True

            return cleaned_data

        # decreasing the submission attempts counter
        self.session_record.submission_attempts_left -= 1

        if timezone.now() > self.session_record.confirmation_code_expiry:
            # the session is expired
            self.add_error(None, ValidationError(
                message='We apologize, but the time for posting has expired.',
                code='time_expired'
            ))
            self.session_record.delete()
            self.critical_error = True

            return cleaned_data

        # hashing the values to compare them with those stored in the db
        email = hash_value(cleaned_data.get('email', ''))
        code = hash_value(str(cleaned_data.get('code', '')))

        if self.session_record.email_hash != email:
            # the email entered does not match
            self.add_error('email', ValidationError(
                message='The entered email address does not match the address to which the code was sent. '
                        'Please check your email and request the code again.', code='wrong_email'
            ))
            self.session_record.delete()
            self.critical_error = True

            return cleaned_data

        if self.session_record.confirmation_code_hash != code:
            # the confirmation code entered does not match
            if not self.session_record.validation_attempts_left:
                # user has no code validation attempts left
                self.add_error(None, ValidationError(
                    message='Incorrect code was entered and the number of available attempts '
                            'to validate it has been exhausted. Please try requesting the code again.',
                    code='wrong_code_and_no_validation_attempts'
                ))
                self.session_record.delete()
                self.critical_error = True

                return cleaned_data

            else:
                # user has at least one code validation attempt left
                self.add_error('code', ValidationError(
                    message='Incorrect code entered. Please, request the code again.',
                    code='wrong_code'
                ))

                # decreasing the number of validation attempts available
                # because an unintended validation of the code has just occurred
                self.session_record.validation_attempts_left -= 1
                self.session_record.save()
                return cleaned_data

        return cleaned_data

feedback_form/templates/feedback_form/confirmation_email.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body style="height: 100%;
      font-size: 1.35rem;
      line-height: 125%;
      padding: 8% 10%;
      font-family: system-ui, sans-serif;
      font-weight: 500;
      background-color: lightgray;
      margin-bottom: 1rem;">
  <div style="padding: 15%;
      background-color: white;
      border-radius: 25px;">
    <p style="margin-bottom: 1rem;">Hello!</p>
    <p style="margin-bottom: 1rem;">This is a confirmation email for the contact form. Please enter the code below into the code field on our website:</p>
    <div style="color: white;
      text-align: center;
      background-color: black;
      border-radius: 4px;
      padding: 4px 12px;
      height: 30px;
      font-size: 107%;
      letter-spacing: 2px;
      margin-bottom: 1rem;">
      <table width="100%" cellpadding="0" border="0" cellspacing="0">
        <tbody>
          <tr>
            <td align="center"><strong>{{ code }}</strong></td>
          </tr>
        </tbody>
      </table>
    </div>
    <hr style="color: lightgray;
      margin-bottom: 1rem;">
    <p>If you have not used our site and have not requested a code, please ignore this email.</p>
  </div>
</body>
</html>

feedback_form/templates/feedback_form/feedback_form.html
{% load static %}
<link rel="stylesheet" href="{% static 'feedback_form/css/form_styles.css' %}">
<div id="feedbackFormSection" class="d-flex justify-content-center">
  <div class="col-sm-10 col-md-8 col-lg-6 col-xl-5 px-4 py-4">
    <h2 class="text-center mb-3" id="feedback">Feedback form</h2>
    <form id="feedbackForm" method="post" action="">
      {% csrf_token %}
      <div class="mb-3">
        <label for="id_email" class="form-label fw-semibold">Your email:</label>
        <input type="email" name="email" class="form-control feedback-form-control" maxlength="320" required id="id_email">
        <div id="emailErrors" class="fw-semibold mt-3 text-danger d-none"></div>
      </div>
      <div id="emailConfirmationGroup" class="mb-3 d-none">
        <button type="button" id="confirmEmailButton" class="btn btn-dark fw-semibold px-4 mb-3">Confirm email</button>
        <div class="recaptcha-container">
          <script defer src='https://www.google.com/recaptcha/api.js'></script>
          <div class="g-recaptcha" data-sitekey="{{ recaptcha_public_key }}" data-callback="captchaFilled"></div>
        </div>
        <p id="emailConfirmationGroupErrorMessage" class="fw-semibold mt-3 text-danger d-none"></p>
      </div>
      <p id="generalErrorMessage" class="fw-semibold mb-3 text-danger d-none"></p>
      <p id="generalInfoMessage" class="fw-semibold mb-3 d-none"></p>
      <div id="codeFieldGroup" class="mb-3 d-none">
        <label for="id_code" class="form-label fw-semibold">Confirmation code:</label>
        <input type="text" name="code" class="form-control feedback-form-control" inputmode="numeric" pattern="[0-9]*" maxlength="6" autocomplete="off" required id="id_code">
        <div id="codeErrors" class="fw-semibold mt-3 text-danger d-none"></div>
        <p id="codeFieldGroupErrorMessage" class="fw-semibold mt-3 text-danger d-none"></p>
        <p id="codeFieldGroupValidationCounter" class="fw-semibold mt-3 text-danger d-none"></p>
        <p id="emailResendSection" class="fw-semibold mt-3 d-none"></p>
      </div>
      <div class="mb-3">
        <label for="id_message" class="form-label fw-semibold">Message:</label>
        <textarea name="message" cols="40" rows="5" class="form-control feedback-form-control" placeholder="Enter the message you would like to send us. We will receive it and contact you by email." required id="id_message"></textarea>
        <div id="messageErrors" class="fw-semibold mt-3 text-danger d-none"></div>
      </div>
      <div id="generalFormErrors" class="fw-semibold mt-3 text-danger d-none"></div>
      <div class="mb-3">
        <noscript class="fw-bold text-danger">Please enable JavaScript in your browser to use the form!</noscript>
      </div>
      <button id="submitFormButton" type="submit" class="btn btn-dark w-100 fw-bold mb-3">Send</button>
    </form>
  </div>
</div>

<!-- Validation error modal -->
<div class="modal fade" id="errorModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="errorModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header border-0">
        <h1 class="modal-title fs-5" id="errorModalLabel">Error in filling out the form</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" id="feedbackModalBtnClose"></button>
      </div>
      <div class="modal-body border-0">
        <div id="modalErrorListContainer"></div>
      </div>
      <div class="modal-footer border-0">
        <button type="button" class="btn btn-dark fw-bold mb-3" data-bs-dismiss="modal">Okay</button>
      </div>
    </div>
  </div>
</div>

<script defer type="text/javascript">
  var endpointUrls = {
    codeValidationUrl: "{% url 'ajax_code_validation' %}",
    emailConfirmationUrl: "{% url 'ajax_email_confirmation' %}",
    emailReconfirmationUrl: "{% url 'ajax_email_reconfirmation' %}",
    formSuccessUrl: "{% url 'form_success' %}",
    formValidationUrl: "{% url 'ajax_feedback_form_validation' %}"
  }
</script>

<script defer src="{% static 'feedback_form/js/scripts.js' %}"></script>

feedback_form/templates/feedback_form/form_success.html
<!DOCTYPE html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <style>
      * {
        font-family: Roboto, system-ui, sans-serif;
        font-size: 1.15rem;
      }
    </style>
    <!-- Page title -->
    <title>Success!</title>
  </head>
  <body class="h-100">
    <div class="d-flex justify-content-center align-items-center px-2 h-100">
      <div class="text-center">
        <h1 class="display-4 fw-bold mb-0">Success!</h1>
        <p class="display-6">Your message has been sent!</p>
        <p id="redirectTimer" class="text-secondary fst-italic mt-5">redirecting after 5 seconds...</p>
      </div>
    </div>
    <script defer type="text/javascript">
      redirectTimer = document.getElementById('redirectTimer');
      var secondsRemaining = 5;

      timerInterval = setInterval(function() {
        secondsRemaining--;
        if (secondsRemaining > 0) {
          redirectTimer.textContent = 'redirecting after ' + secondsRemaining;

          if (secondsRemaining > 1) {
            redirectTimer.textContent += ' seconds...'
          } else {
            redirectTimer.textContent += ' second...'
          }

        } else {
          clearInterval(timerInterval);
          {% if not form_redirect_address %}
            const referrerCookie = document.cookie.split('; ').find(row => row.startsWith('ff_referrer='));
            if (referrerCookie) {
              const referrerCookieValue = referrerCookie.split('=')[1];
              if (referrerCookieValue){
                document.cookie = 'ff_referrer' + '=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;'
                window.location.replace(referrerCookieValue);
              }
            } else {
              window.location.href = window.location.origin + "/";
            }
          {% else %}
            document.cookie = 'ff_referrer' + '=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;';
            window.location.replace('{{ form_redirect_address }}');
          {% endif %}
        }
      }, 1000);
    </script>
  </body>
</html>

feedback_form/templates/feedback_form/submitted_email_report.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body style="height: 100%;
      font-size: 1.35rem;
      line-height: 125%;
      padding: 8% 10%;
      font-family: system-ui, sans-serif;
      font-weight: 400;
      background-color: lightgray;
      margin-bottom: 1rem;">
  <div style="padding: 15%;
      background-color: white;
      border-radius: 25px;">
    <p style="margin-bottom: 1rem;">Hello!</p>
    <p style="margin-bottom: 1rem;">A new letter has been sent via the feedback form!</p>
    <p style="margin-bottom: 1rem; font-weight: 500;">Sender: <a href="mailto:{{ user_email }}" style="color: black; font-weight: bold;">{{ user_email }}</a></p>
    <p style="margin-bottom: 1rem; font-weight: 500;">Text:</p>
    <p style="margin-bottom: 1rem;">{{ user_message }}</p>
    <hr style="color: lightgray; margin-bottom: 1rem;">
    <p style="color: gray; font-size: 1.1rem;">This letter is automatically generated. No need to try to reply to it, reply to the sender of the letter above.</p>
  </div>
</body>
</html>